### ISSUE TITLE
Slow tags when using "better Bibtex for Zotero" plugin with autoexport

### ISSUE THREAD

**Issue by dsimat** [retorquere/zotero-better-bibtex#1125]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification
Tagging items seems to take ages if I have a lot of tags and I have "Better Bibtex" auto-export set up. This is a follow up from the [Zotero forums](https://forums.zotero.org/discussion/75413/slow-tags-when-using-better-bibtex-for-zotero-plugin?new=1).

## Non-export problems with BBT

Report ID: Y5FQUNB3-euc

**Comment by retorquere** [comment]
I take it you mean "with auto-export setup", rather than just "with BBT installed"?

**Comment by dsimat** [comment]
Yes, that's what I mean.

**Comment by retorquere** [comment]
Can you try replicating the problem with 3393 and send a new log? It looks like BBT is ignoring its cache, that would explain a lot.

**Comment by dsimat** [comment]
I have done so.

Report ID: THFEIJT8-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3394](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3394.xpi) ("startHidden")

Install in Zotero by downloading [test build 5.1.45.3394](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3394.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dsimat** [comment]
Report ID: JLVC95IB-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3397](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3397.xpi) ("disable JRF on immediate auto-export")

Install in Zotero by downloading [test build 5.1.45.3397](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3397.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
I think I have something. Can you try 3397?

**Comment by retorquere** [comment]
When I say try, I mean like the last time:

* turn on debug output logging if it isn't on
* go into the BBT preferences and kick off the auto-export you have manually, twice (letting the first finish before you kick off the second)
* submit a new BBT error report 

The first will be slow, but the second should use the now-filled cache.

**Comment by dsimat** [comment]
Done. Report ID: HAEHC8KM-euc

The second one was not any slower than the first.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3398](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3398.xpi) ("more logging -- cache still off?")

Install in Zotero by downloading [test build 5.1.45.3398](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3398.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Still not picking up the cache. Can you try again with 3398? I can't replicate the problem here but I can see in your case the cache is not being used.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3399](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3399.xpi) ("always override JRF, not just for on-change")

Install in Zotero by downloading [test build 5.1.45.3399](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3399.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dsimat** [comment]
Report ID: 99LBZVKZ-euc

There was a huge difference now. After the first export I saw that "cashed" went to 100%, and the second export was very fast.

**Comment by retorquere** [comment]
I had set up a change that would only work when auto-export was set to on-change; 3399 has the change but it is always on.

**Comment by dsimat** [comment]
I always set auto-export to disabled after the issues started, hence I could not see the change.

**Comment by retorquere** [comment]
So here's the thing -- for auto-exports, you (obviously) really want the caching on. BBT is pretty slow on it's own and really needs the cache, certainly for auto-export. The issue you stumbled upon is that the JabRef-4 compatible metadata isn't safely cachable, so BBT turns off cache if you have JabRef compatibility set to 4 (which I still think is a worse format than `3`). 3399 ignores the JabRef format preference for auto-exports and behaves like JabRef compatibility is set to `off`.

I can do one of two things -- I can keep the 3399 behavior and assume `off` for auto-exports, or I can assume `3` for autoexports when you have the preference set to `4`. Neither one is really ideal, but I could make a case for both:

1. Behave like it's set to `3` best preserves intent -- you wanted JR compatibility, you get JR compatibility. The major difference is the way collections are exported; `4` has a `groups` field in the reference (which varies per export, which is why it's uncachable), `3` has the group assignments at the bottom, outside the reference. But the same information is in the file, just written down differently, and if you import it in JabRef, you get the same result. Well, almost -- if you have two collections named (e.g.) `lit-review` in different places in your collection hierarchy in the same export, I can't export these correctly. That's not just for me, the JR format 4 makes it impossible to have two collections with the same name *across the bib file*. JR format 3 did not have this problem. In any case, anything that can be exported safely to JR4 can also be exported to JR3.
2. I behave like it's off. The main target for auto-export is keeping stuff live for article authoring, not mainly to keep JabRef fed after all.

**Comment by retorquere** [comment]
Or

3. I can warn in the preferences about the cache being off when you select format `4` and leave everything as-is.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3400](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3400.xpi) ("warn about JRF4")

Install in Zotero by downloading [test build 5.1.45.3400](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3400.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dsimat** [comment]
The warning is there. However, the cache is still not disabled when opting for JR 4 compatibility.

Report ID: HJ2KWQ8R-euc

**Comment by retorquere** [comment]
Yeah I'm considering keeping the warning but also the 3399 behavior. The cache will still be disabled for manual (right-click) exports (so the warning is still valid), but when JR4 is selected, auto-exports would assume no-JR. I just don't see a major case for JR4 auto-exports, and a larger chance that people would be affected by the worse performance.

**Comment by dsimat** [comment]
But then auto-exporting with JR4 could land the user in trouble if there are two collections with the same name, as mentioned earlier.

**Comment by dsimat** [comment]
OK. I just don't understand the argument in favor of keeping the 3399 behavior in addition to the warning. The user should somehow be aware that the JabRef format preference for auto-exports is ignored.

**Comment by retorquere** [comment]
The argument would be that you could still occasionally export to JR4 but that auto-exports would ignore it, without affecting the cache. Changing any BBT preference will drop the cache entirely. But it's true that it's not nice that you set things one way and auto-export behaves another way.

**Comment by dsimat** [comment]
Exactly. The rules seem to be different for manual export and auto-export. IMHO this is confusing (especially if this difference is not mentioned).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.45.3403](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3403.xpi) ("if the user wants JR4, Jr4 it is")

Install in Zotero by downloading [test build 5.1.45.3403](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.45.3403.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by dsimat** [comment]
This works and is how I personally would prefer it.

Report ID: 9UK5AKET-euc

Thanks for sorting this out.

**Comment by retorquere** [comment]
3403 is out as a new release

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.101.4314](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4314.xpi) ("fixes #1125")

Install in Zotero by downloading [test build 5.1.101.4314](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4314.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
