### ISSUE TITLE
Brace balancer throws error

### ISSUE THREAD

**Issue by mmwood** [retorquere/zotero-better-bibtex#177]
I get the above error message (under the title [JavaScript Application]) when trying to export my library with the Better BibTex format.  I have no problems exporting with Zotero's usual BibTex export (well, of course, except for the terrible default keys, which is why I use better bibtex in the first place...)

Below is the Zotero Error Report (Report ID: 2143587191).  I didn't bring this up in the Zotero forums because as far as I can tell, it is just a better-bibtex issue.

[JavaScript Error: "uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [mozIStorageConnection.executeSimpleSQL]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://zotero/content/xpcom/db.js :: Zotero.DBConnection.prototype.query :: line 149"  data: no] [QUERY: create table betterbibtex.autoexport ( id INTEGER PRIMARY KEY NOT NULL DEFAULT NULL, collection not null, path not null, exportOptions not null, exportedRecursively CHECK(exportedRecursively in ('true', 'false')), status CHECK(status in ('pending', 'error', 'done')), foreign key (exportOptions) references exportoptions(id) )] [ERROR: table autoexport already exists]"]
[JavaScript Error: "this.skipFields is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 975}]
[JavaScript Error: "this.skipFields is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 975}]
[JavaScript Error: "this.skipFields is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 975}]
[JavaScript Error: "this.skipFields is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 975}]

version => 4.0.26.3, platform => MacIntel, oscpu => Intel Mac OS X 10.10, locale => en-US, appName => Zotero, appVersion => 4.0.26.3, extensions => Zotero Better Bib(La)Tex (0.8.37, extension), Zotero Word for Mac Integration (3.5.7.SA.4.0.26.3, extension), Zotero LibreOffice Integration (3.5.9.SA.4.0.26.3, extension), Default Browser Helper (600, plugin), Adobe Acrobat NPAPI Plug-in, Version 11.0.10 (11.0.10, plugin), QuickTime Plug-in 7.7.3 (7.7.3, plugin), Java Applet Plug-in (15.0.0, plugin), SharePoint Browser Plug-in (14.4.1, plugin), Shockwave Flash (11.9.900.152, plugin)

Thanks!

**Comment by AllThatIsTheCase** [comment]
Should be fixed now. Sorry for the disruption.

**Comment by mmwood** [comment]
I updated BetterBibTex and still get the same error message when trying to export.

Here is the error report: (ID: 1137659910)

[JavaScript Error: "uncaught exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [mozIStorageConnection.executeSimpleSQL]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://zotero/content/xpcom/db.js :: Zotero.DBConnection.prototype.query :: line 149"  data: no] [QUERY: alter table betterbibtex.keys rename to _keys_] [ERROR: there is already another table or index with this name: _keys_]"]
[JavaScript Error: "Zotero.BetterBibTeX is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 1001}]
[JavaScript Error: "Zotero.BetterBibTeX is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 1001}]
[JavaScript Error: "Zotero.BetterBibTeX is undefined" {file: "/Users/mmwood/Library/Application Support/Zotero/Profiles/7e8pqiiu.default/zotero/translators/Better BibTeX.js" line: 1001}]

version => 4.0.26.3, platform => MacIntel, oscpu => Intel Mac OS X 10.10, locale => en-US, appName => Zotero, appVersion => 4.0.26.3, extensions => Zotero Word for Mac Integration (3.5.7.SA.4.0.26.3, extension), Zotero LibreOffice Integration (3.5.9.SA.4.0.26.3, extension), Zotero Better Bib(La)Tex (0.8.40, extension), Default Browser Helper (600, plugin), Adobe Acrobat NPAPI Plug-in, Version 11.0.10 (11.0.10, plugin), QuickTime Plug-in 7.7.3 (7.7.3, plugin), Java Applet Plug-in (15.0.0, plugin), SharePoint Browser Plug-in (14.4.1, plugin), Shockwave Flash (11.9.900.152, plugin)

**Comment by AllThatIsTheCase** [comment]
Can you report the error via "report zotplus error"? If you click through,
you'll get a red url which you can post here. When pasting the log here
github formats away relevant information.

**Comment by AllThatIsTheCase** [comment]
Can you give this versino a try: https://dl.dropboxusercontent.com/u/5300806/zotero-better-bibtex-0.8.40.xpi

**Comment by mmwood** [comment]
I did a report zotplus error.  Here is the Report ID: 
http://is.gd/UrLaD8

Now I will try the new version and then let you know if it works.

**Comment by mmwood** [comment]
The new version you pasted above gives the same error message.  I reported a ZotPlus Error error with report ID
http://is.gd/u3Ay2h

**Comment by AllThatIsTheCase** [comment]
http://is.gd/UrLaD8 has an autozotbib error; I don't think it actually affects BBT, but you might want to have the autozotbib author look into it. http://is.gd/u3Ay2h does show an error, but it's not the error you outlined above with `ID: 1137659910`. Can you do the following for me:

Go into Preferences->Advanced, check "enable after restart", do a full restart of firefox (all windows must be closed, or it won't work), and then right-click an entry you were trying to export that errored out, and then select "report zotplus error" from that menu, and again paste the resulting URL here. It will give me the reference plus the full error.

**Comment by AllThatIsTheCase** [comment]
the weird thing is thought that neither of these two reports show the earlier problem you noted under `ID: 1137659910`.

**Comment by AllThatIsTheCase** [comment]
I really could use a sample to trace this down.

**Comment by AllThatIsTheCase** [comment]
The current error is 
    [JavaScript Error: "Expected "\\textleftbrace", "\\textrightbrace", "\\{", "\\}", [^\\] or any character but end of input found."]

I know where it happens, but not what triggers it; with a sample I can probably fix this easily.

**Comment by AllThatIsTheCase** [comment]
Closed for inactivity

**Comment by retorquere** [comment]
Don't hesitate to re-open if you want BTW
