### ISSUE TITLE
Open element in Zotero through citekey

### ISSUE THREAD

**Issue by houshuang** [retorquere/zotero-better-bibtex#769]
Amazing plugin. I am wondering if there is any way of opening an item in Zotero through a URL if you only new the citekey. Let's say I have an item in Zotero with the citekey johnson2000molecules... Would it be possible to do something like zotero://bbt:johsnon2000molecules etc, and have Zotero open (or activate) with the right publication selected?

Thank you!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4710](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4710.issue-769.xpi) ("add item keys").

**Comment by retorquere** [comment]
I've hooked into the existing select mechanism; `zotero://select/items/bbt:<citekey>` (user library) or `zotero://select/items/bbt:{<group id>}<citekey>` should work in 4710 (`<group id>` of `0` is the same as user library) but I haven't tested it since I have no idea how it is actually used.

**Comment by dbobak** [comment]
Does not work. At all - Zotero partially hangs at start with message "Better BibTeX: Starting key manager...". "Partially" means, that menus in Zotero works, but the content of the window is inactive. 

Error report ID: AZRRUZK5

Tested with BBT 4710; with later (4719, 4721) the error does not appear but also the link does not work.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4725](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4725.issue-769.xpi) ("DB upgrade").

**Comment by dbobak** [comment]
4725: links doesn't work, neither `zotero://select/items/bbt:Adams1999Lower` nor `zotero://select/items/bbt:{0}Adams1999Lower`

**Comment by retorquere** [comment]
How do you test this? I have no idea how these work.

**Comment by dbobak** [comment]
1. Just paste the link to Chrome or Firefox. Zotero window gets focus, but the cursor do not follow the desired position.
2. Create link in Atom and click it. Result is the same as above.

**Comment by retorquere** [comment]
I've tried this; in chrome, it just googles that link, and in zotero, it tries to open Zotero a second time (which fails, because the profile is locked by the running Zotero). 

I can try at my work desktop which runs Linux; right here I only have a macbook.

4727 should drop here in a bit and that will have more debug logging; it'd be helpful to get a new debug log after accessing such a link.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4727](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4727.issue-769.xpi) ("debugging for #769").

**Comment by dbobak** [comment]
When you paste the link into the address bar in Chrome (but do not press `enter` then) you'll see pull-down menu with options: open link in Chrome or search in Google. Choose the first :)

The build 4727 is working as it's expected: Zotero windows gets focus and the cursor follows to the reference. But the only in the version without group ID, ie:
`zotero://select/items/bbt:Adams1999Lower` - works
`zotero://select/items/bbt:{0}Adams1999Lower` - does not work.

Report ID: 882ZXTWH

**Comment by retorquere** [comment]
Well at least the behavior is consistent now -- Chrome *also* wants to open a 2nd Zotero instance, which is not allowed because profile locked, yada yada 😆. Don't know how I've screwed up my machine (which I likely did), but this POS is due for a replacement anyhow. Just a few months more. The log had good information though -- 4736 will drop in a few minutes with a fix.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4736](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.36.4736.issue-769.xpi) ("IDs are uri-encoded").

**Comment by retorquere** [comment]
4736 should fix it.

**Comment by dbobak** [comment]
Sorry, but still no banana with 4736.
Link with the group ID (`zotero://select/items/bbt:{0}Adams1999Lower`) still does not work

Report ID: 8TX6JDKR

**Comment by retorquere** [comment]
Still the same error. 4745 adds more logging.

Sorry to have to lean on you guys for testing, but I can't trigger it here.

**Comment by dbobak** [comment]
You're doing a great piece of job with BBT, I'm just glad to help :)

Report ID for 4745: DM5UX6BX

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 4747](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.37.4747.issue-769.xpi) ("return libraryID, not unparsed lib").

**Comment by retorquere** [comment]
4747 should do the trick (but then I claimed that before)

**Comment by dbobak** [comment]
Indeed. 4747 works :) Thanks!

**Comment by mijalche** [comment]
very interesting feature!
I have a question this functions very well for My Library, however it does not function for the Group Libraries. 
I assume is connected with the Group ID. Where I can find the Group ID?

**Comment by dbobak** [comment]
I don't use groups, so I haven't tested it before. But:
1. I'm checking the group ID in the Zotero website. And got, for example: 290013.
2. Trying to get link to the item: `zotero://select/items/bbt:{290013}NerudaNerudova2013MiddleUpper`
3. Link doesn't work.

I'm not sure if it is a problem of BBT or wrong group ID; how to check the group ID is described [here](https://programminghistorian.org/lessons/deprecated/intro-to-the-zotero-api), but it seems to be deprecated. 

Anyway, the error report ID is: 6SRKPGD9

**Comment by retorquere** [comment]
The group ID is a local thing I think. 

The debug report won't help -- the feature works as intended (select by group ID + citekey), but how you discover the group ID is outside BBTs scope. The "Get BibTeX URL" will likely have the lib id, but I can't test where I am now. See also https://forums.zotero.org/discussion/24241/linking-to-zotero-items-via-zotero-select and http://protips.maxmasnick.com/zotero-quickly-get-links-to-library-items-using-zotero-slash-slash-url-scheme-links .

**Comment by dbobak** [comment]
Yes! The "BibLaTeX URL" options gives the correct library ID and the links are ok now.

**Comment by mijalche** [comment]
Excellent! Links are working for me, also.
For the others: you get the BibLaTeX URL by right click on the group library name. It is the number after .../better-bibtex/library?/NUMBER
